name: FluidNavigationDemo
options:
  bundleIdPrefix: com.arunabhdas.fluidnavigation
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  FluidNavigationDemo:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.arunabhdas.fluidnavigation.demo
      INFOPLIST_FILE: Resources/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      DEVELOPMENT_TEAM: YOUR_TEAM_ID  # Optional
    dependencies:
      - package: FluidNavigation
        product: FluidNavigation

packages:
  FluidNavigation:
    path: ../../  # Path to your FluidNavigation package root

schemes:
  FluidNavigationDemo:
    build:
      targets:
        FluidNavigationDemo: all
    run:
      config: Debug
    archive:
      config: Release
